# Site settings
title: מוחקים את המאגר הביומטרי
email: team@no2bio.org
url: https://no2bio.github.io

baseurl: /mk-personal

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#d12229'
  links_hover: '#91170a'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty

collections:
  mks:
    output: true
