# Site settings
title: מוחקים את המאגר הביומטרי
description: האם נבחרי הציבור ימחקו את המאגר הביומטרי או יפקירו את בטחונך? זה הזמן לשכנע אותם
email: team@no2bio.org
url: http://dropthepilot.no2bio.org
baseurl: 

ogimage: /img/poster.jpg
twitter_username: no2bio

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#d12229'
  links_hover: '#91170a'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty

collections:
  mks:
    output: true
